### ISSUE TITLE
how to group icons

### ISSUE THREAD

**Issue by leizard** [GittiHab/jquery-emojiarea#2]
I use your plugin but I doesn't group the icons like the screenshot. How could I archive it? thank you

**Comment by GittiHab** [comment]
@leizard I don't exactly understand what you mean? If I download the repository and open the example (which uses the files of the plugin you would be using), the icons are grouped like in the screenshot. Are you sure you downloaded my repo and not the original one from `diy`?

Please give me more details if you still have the problem.

**Comment by GittiHab** [comment]
No answer. So I will close this issues.
