### ISSUE TITLE
How can get emoji when fetch data from database and show in div

### ISSUE THREAD

**Issue by devendrawebdeveloper** [GittiHab/jquery-emojiarea#3]
Hello,

Plugin work fine.just need show emoji in div when fetch paragraph from database.

**Comment by GittiHab** [comment]
Hello @devendrawebdeveloper,
could you please state your problem more clear? Otherwise I do not know, what you want to know.

**Comment by devendrawebdeveloper** [comment]
Hello 

I am using your jquery library for emoji in textarea after that user submitted form and save in database then i fetched from database and show in testimonial div html.but emoji looks like string.:smile:

**Comment by GittiHab** [comment]
This is in fact not supported by this plugin (yet). You might want to extend the library yourself (I would be happy if you made Pull Request in this case) or combine it with another library like the one from [linyows](https://github.com/linyows/jquery-emoji).

I hope this helps?
