### ISSUE TITLE
Ajax spit out data emoji string expression how to change

### ISSUE THREAD

**Issue by qzmly100** [GittiHab/jquery-emojiarea#4]
emoji expressions?

**Comment by GittiHab** [comment]
Hello,
is this issue still relevant? If so, could you please specify your problem more close?

**Comment by socialinfotech215** [comment]
in this demo i can send emoji name it's good but how can i send emoji image in this demo.?

**Comment by socialinfotech215** [comment]
can you please help me...

**Comment by GittiHab** [comment]
@socialinfotech215 do you mean that the final string is something like `Hello :smile:`? instead of `Hello 😄`? If you would like the image to be in the string you will have the parse the string and replace :*: with the according image.
