### ISSUE TITLE
Replacing text on a page with emoji image if detected

### ISSUE THREAD

**Issue by Callump01** [GittiHab/jquery-emojiarea#6]
Hi,

Is it possible to replace all the text on a page with the emoji image if the relevant trigger is detected?

For example, `:smile:` is replaced with 😄  once detected, not necessarily in a text box.

Thanks,
Callum

**Comment by GittiHab** [comment]
Hi Callum,

I am not maintaining this anymore so I do not know for sure. As far as I remember, you will have to use another library (but there are some out there that do this, as I have used them before).

Good luck with it!
